# To run this specifically:
# docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from fe
# docker-compose -f docker-compose.ci.yml down

version: '3.7'
services:
  rust-db:
    hostname: my-rust-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=myrustdb
      - POSTGRES_USER=myrustuser
      - POSTGRES_PASSWORD=myrustpassword
    ports:
      - "15433:5432"
    volumes:
      - ./docker/db/rust-init:/docker-entrypoint-initdb.d

  rust-server:
    build: ./rust
    ports:
      - "8002:8002"
    depends_on:
      - rust-db

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile.ci
    ports:
      - "1234:1234"
    environment:
      # Injected from Github workflow's secret
      - SECURE_API_PORT=${SECURE_API_PORT}
    depends_on:
      - rust-server

