version: '3.7'
services:
  node-db:
    hostname: my-node-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=mynodedb
      - POSTGRES_USER=mynodeuser
      - POSTGRES_PASSWORD=mynodepassword
    ports:
      - "15432:5432"
    volumes:
      - ./docker/db/node-init:/docker-entrypoint-initdb.d

  rust-db:
    hostname: my-rust-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=myrustdb
      - POSTGRES_USER=myrustuser
      - POSTGRES_PASSWORD=myrustpassword
    ports:
      - "15433:5432"
    volumes:
    #   - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/db/rust-init:/docker-entrypoint-initdb.d
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    # networks:
    #   - rust-backend

  rust-server:
    build: ./rust
    ports:
      - "8000:8000"
    depends_on:
      - rust-db
    # networks:
    #   - rust-backend

# Default: twitter-clone_default i.e. <app-name>_default
# networks:
#   rust-backend:
#     name: rust_backend_name