version: '3.7'
services:
  db:
    hostname: my-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=mytwitter
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "15432:5432"
    volumes:
    #   - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/db/init:/docker-entrypoint-initdb.d
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf