# This starts up DB, API server and frontend app containers.
# Use only for smoke tests. Code changes are not reflected here.

# To run this specifically:
# docker-compose -f docker-compose.dev.yml up
# docker-compose -f docker-compose.dev.yml down

version: '3.7'
services:
  rust-db:
    hostname: my-rust-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=myrustdb
      - POSTGRES_USER=myrustuser
      - POSTGRES_PASSWORD=myrustpassword
    ports:
      - "15433:5432"
    volumes:
      - ./docker/db/rust-init:/docker-entrypoint-initdb.d

  rust-server:
    build: ./rust
    ports:
      - "8002:8002"
    depends_on:
      - rust-db

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - SECURE_API_HOST=localhost
      - SECURE_API_PORT=8002
    depends_on:
      - rust-server

