# Starts the DB and API server only.
# Use to quickly bring up and teardown the backend environment
# while you develop on the frontend code.
# Code changes on backend are not reflected in container.

# Default file for development:
# docker-compose up
# docker-compose down

version: '3.7'
services:
  rust-db:
    hostname: my-rust-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=myrustdb
      - POSTGRES_USER=myrustuser
      - POSTGRES_PASSWORD=myrustpassword
    ports:
      - "15433:5432"
    volumes:
    #   - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/db/rust-init:/docker-entrypoint-initdb.d
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf

  rust-server:
    build:
      context: ./rust
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - rust-db
