# To run this specifically:
# docker-compose -f docker-compose.ci.yml up
# docker-compose -f docker-compose.ci.yml down

version: '3.7'
services:
  rust-db:
    hostname: my-rust-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=myrustdb
      - POSTGRES_USER=myrustuser
      - POSTGRES_PASSWORD=myrustpassword
    ports:
      - "15433:5432"
    volumes:
    #   - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/db/rust-init:/docker-entrypoint-initdb.d
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf

  rust-server:
    build: ./rust
    ports:
      - "8000:8000" # for debug (dev)
      - "8002:8002" # for release
    depends_on:
      - rust-db
