# Latest versions may have breaking changes
# FROM mcr.microsoft.com/playwright:focal

FROM mcr.microsoft.com/playwright:v1.24.1

COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .

RUN npm run build

CMD npm run test