# Notes:
# - Has to be 0.0.0.0 when starting inside docker container
# - For local dev, it can be default (localhost)
# - Make sure port is mapped in docker-compose file

[debug]
address = "0.0.0.0"
port = 8001

[release]
address = "0.0.0.0"
port = 8002

[default]
my_rocket_var_1 = "This is a value from Rocket.toml file"
my_rocket_var_2 = 1.23

[default.databases.myrustdb]
# within container (for CI uses)
# hostname "rust-db" is defined in docker-compose file
url = "postgresql://myrustuser:myrustpassword@rust-db:5432/myrustdb"
# external server accessing into container (for local dev)
# url = "postgresql://myrustuser:myrustpassword@localhost:15433/myrustdb"
